version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
      - "4040:4040"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app_db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
